name: Pipeline [test -> build -> deploy]

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - test
          - dev
          - preprod
          - prod
        default: 'dev'
      version:
        description: Image version
        type: string
        required: true
      docker_registry:
        description: Docker registry
        required: true
        default: 'ghcr.io'
        type: choice
        options:
          - 'ghcr.io'
          - 'quay.io'
      registry_org:
        description: Docker registry organisation
        required: true
        default: 'ministryofjustice'
        type: choice
        options:
          - 'ministryofjustice'
          - 'hmpps'
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: true
        type: boolean
      docker_multiplatform:
        description: docker multiplatform build or not
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build docker image from hmpps-github-actions
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v1
    with:
      docker_registry: ${{ inputs.docker_registry || 'ghcr.io' }}
      registry_org: ${{ inputs.registry_org || 'ministryofjustice' }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: ${{ inputs.docker_multiplatform || false }}

  deploy_test:
    name: Deploy to the test environment
    needs:
      - build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-test')
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
    secrets: inherit
    with:
      environment: 'test'
      app_version: '${{ needs.build.outputs.app_version }}'
  
  deploy_dev:
    name: Deploy to the development environment
    needs:
      - build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-dev')
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
    secrets: inherit
    with:
      environment: 'development'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_preprod:
    name: Deploy to pre-production environment
    needs: 
      - build
      - deploy_dev
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_prod:
    name: Deploy to production environment
    needs: 
      - build
      - deploy_preprod
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build.outputs.app_version }}'